import { createFileRoute } from "@tanstack/react-router";
import {
  getCatalogCards,
  getCatalogSummary,
  type CatalogCardsResult,
  type CatalogSummaryResult,
} from "@/lib/catalog.server";

const EDGE_CACHE = "public, s-maxage=300, stale-while-revalidate=3600";
const BROWSER_CACHE = `public, max-age=0, ${EDGE_CACHE.slice("public, ".length)}`;

export interface CatalogApiLoaders {
  getCards: () => Promise<CatalogCardsResult>;
  getSummary: () => Promise<CatalogSummaryResult>;
}

const defaultLoaders: CatalogApiLoaders = {
  getCards: getCatalogCards,
  getSummary: getCatalogSummary,
};

async function createEtag(body: string): Promise<string> {
  const bytes = new TextEncoder().encode(body);
  const digest = await globalThis.crypto.subtle.digest("SHA-256", bytes);
  const hex = Array.from(new Uint8Array(digest), (byte) =>
    byte.toString(16).padStart(2, "0"),
  ).join("");
  return `"${hex}"`;
}

function etagMatches(header: string | null, etag: string): boolean {
  if (!header) return false;
  const normalize = (value: string) => value.trim().replace(/^W\//, "");
  const normalizedEtag = normalize(etag);
  return header
    .split(",")
    .some((candidate) => candidate.trim() === "*" || normalize(candidate) === normalizedEtag);
}

/** Exported separately so focused tests can exercise HTTP caching semantics. */
export async function handleCatalogRequest(
  request: Request,
  loaders: CatalogApiLoaders = defaultLoaders,
): Promise<Response> {
  const summaryOnly = new URL(request.url).searchParams.get("summary") === "1";
  let payload: CatalogSummaryResult | (CatalogCardsResult & { total: number });

  if (summaryOnly) {
    payload = await loaders.getSummary();
  } else {
    const catalog = await loaders.getCards();
    payload = { ...catalog, total: catalog.features.length };
  }

  const body = JSON.stringify(payload);
  const etag = await createEtag(body);
  const headers = new Headers({
    "Cache-Control": BROWSER_CACHE,
    "CDN-Cache-Control": EDGE_CACHE,
    "Content-Type": "application/json; charset=utf-8",
    ETag: etag,
    Vary: "Accept-Encoding",
  });

  if (etagMatches(request.headers.get("If-None-Match"), etag)) {
    return new Response(null, { status: 304, headers });
  }

  return new Response(body, { status: 200, headers });
}

// The route tree is generated by the TanStack Vite plugin. The cast keeps a
// standalone `tsc --noEmit` run valid before that generated file is refreshed.
export const Route = createFileRoute("/api/catalog" as never)({
  server: {
    handlers: {
      GET: async ({ request }: { request: Request }) => handleCatalogRequest(request),
    },
  },
});
