/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapPreviewRouteImport } from './routes/sitemap-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRefreshFeaturesRouteImport } from './routes/api/public/refresh-features'
import { Route as ApiPublicGscSyncRouteImport } from './routes/api/public/gsc-sync'

const SitemapPreviewRoute = SitemapPreviewRouteImport.update({
  id: '/sitemap-preview',
  path: '/sitemap-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRefreshFeaturesRoute =
  ApiPublicRefreshFeaturesRouteImport.update({
    id: '/api/public/refresh-features',
    path: '/api/public/refresh-features',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGscSyncRoute = ApiPublicGscSyncRouteImport.update({
  id: '/api/public/gsc-sync',
  path: '/api/public/gsc-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap-preview': typeof SitemapPreviewRoute
  '/api/public/gsc-sync': typeof ApiPublicGscSyncRoute
  '/api/public/refresh-features': typeof ApiPublicRefreshFeaturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap-preview': typeof SitemapPreviewRoute
  '/api/public/gsc-sync': typeof ApiPublicGscSyncRoute
  '/api/public/refresh-features': typeof ApiPublicRefreshFeaturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap-preview': typeof SitemapPreviewRoute
  '/api/public/gsc-sync': typeof ApiPublicGscSyncRoute
  '/api/public/refresh-features': typeof ApiPublicRefreshFeaturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap-preview'
    | '/api/public/gsc-sync'
    | '/api/public/refresh-features'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap-preview'
    | '/api/public/gsc-sync'
    | '/api/public/refresh-features'
  id:
    | '__root__'
    | '/'
    | '/sitemap-preview'
    | '/api/public/gsc-sync'
    | '/api/public/refresh-features'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapPreviewRoute: typeof SitemapPreviewRoute
  ApiPublicGscSyncRoute: typeof ApiPublicGscSyncRoute
  ApiPublicRefreshFeaturesRoute: typeof ApiPublicRefreshFeaturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap-preview': {
      id: '/sitemap-preview'
      path: '/sitemap-preview'
      fullPath: '/sitemap-preview'
      preLoaderRoute: typeof SitemapPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-features': {
      id: '/api/public/refresh-features'
      path: '/api/public/refresh-features'
      fullPath: '/api/public/refresh-features'
      preLoaderRoute: typeof ApiPublicRefreshFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gsc-sync': {
      id: '/api/public/gsc-sync'
      path: '/api/public/gsc-sync'
      fullPath: '/api/public/gsc-sync'
      preLoaderRoute: typeof ApiPublicGscSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapPreviewRoute: SitemapPreviewRoute,
  ApiPublicGscSyncRoute: ApiPublicGscSyncRoute,
  ApiPublicRefreshFeaturesRoute: ApiPublicRefreshFeaturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
